# Site settings
title: Vivek Badiani - Personal Portfolio
author: Vivek Badiani
email: vivekbadiani@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my personal website. I am a Scientist and Software Engineer
  specializing in Energy, Fintech and Chemistry.
baseurl: "" # the subpath of your site, e.g. /blog. If hosted at username.github.io, this is ""
url: "https://viv-bad.github.io" # your site's hostname

# Social media links (replace with your own)
github_username: viv-bad
linkedin_username: vivek-badiani
# twitter_username: yourtwitterhandle
# Add other social media if needed:
google_scholar_id: 86YrbyUAAAAJ&hl
# researchgate_profile: Your-ResearchGate-Profile

# Build settings
theme: minima # Set to null if you are providing all your layouts and styles
# Alternatively, you can use a theme like 'minima':
# theme: minima
#
# If not using a theme, you might need to specify plugins for basic functionality
plugins:
  - jekyll-feed # For an RSS feed, especially if you add a blog
  - jekyll-seo-tag # For better SEO

# Navigation pages (used in _includes/navigation.html)
nav_pages:
  - name: Home
    url: /
  # - name: About
  #   url: / # Points to homepage, can be a separate about.md if preferred
  - name: Projects
    url: /projects/
  - name: Publications
    url: /publications/
  - name: CV
    url: /cv/
  - name: Posts
    url: /posts/ # Add this if you plan to use the _posts folder for a blog

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal list.
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#

include:
  - _pages # If you're using a _pages directory

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - .idea/

# Optional: Setup for a simple blog listing page
# This assumes you might create a `blog.md` in `pages/` with layout `page` or a custom `blog_index` layout
# to list posts.
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post" # You'd need to create a _layouts/post.html
      author: "Vivek Badiani"
# --- Collections (if you want more structured content types beyond posts) ---
# collections:
#   my_collection:
#     output: true
#     permalink: /:collection/:name
