# Site settings
title: Vivek Badiani - Software Engineer & Scientist
author: Vivek Badiani
email: vivekbadiani@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Full-Stack Software Engineer with PhD in Chemistry. Specializing in 
  renewable energy, fintech, and materials science. Experienced in 
  Python, JavaScript, React, and scientific computing.
baseurl: "" # the subpath of your site, e.g. /blog. If hosted at username.github.io, this is ""
url: "https://viv-bad.github.io" # your site's hostname

# Social media links
github_username: viv-bad
linkedin_username: vivek-badiani
# twitter_username: yourtwitterhandle
google_scholar_id: 86YrbyUAAAAJ&hl
# researchgate_profile: Your-ResearchGate-Profile

# Build settings
theme: minima
plugins:
  - jekyll-feed # For an RSS feed
  - jekyll-seo-tag # For better SEO

# Navigation pages (used in _includes/navigation.html)
nav_pages:
  - name: Home
    url: /
  - name: Projects
    url: /projects/
  - name: Publications
    url: /publications/
  - name: CV
    url: /cv/
  - name: Posts
    url: /posts/

# Include _pages directory
include:
  - _pages

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - .idea/

# Defaults for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Vivek Badiani"
